# Models

## How to Develop Vanilla LSTMs

In [1]:
from random import randint
from numpy import array
from numpy import argmax
# generate a sequence of random numbers in [0, n_features)
def generate_sequence(length, n_features):
  return [randint(0, n_features-1) for _ in range(length)]
# one hot encode sequence
def one_hot_encode(sequence, n_features):
  encoding = list()
  for value in sequence:
    vector = [0 for _ in range(n_features)]
    vector[value] = 1
    encoding.append(vector)
  return array(encoding)
# decode a one hot encoded string
def one_hot_decode(encoded_seq):
  return [argmax(vector) for vector in encoded_seq]
# generate random sequence
sequence = generate_sequence(25, 100)
print(sequence)
# one hot encode
encoded = one_hot_encode(sequence, 100)
print(encoded)
# one hot decode
decoded = one_hot_decode(encoded)
print(decoded)

[57, 83, 86, 95, 60, 94, 27, 68, 2, 89, 81, 43, 10, 9, 68, 16, 83, 98, 13, 61, 90, 44, 10, 45, 3]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[57, 83, 86, 95, 60, 94, 27, 68, 2, 89, 81, 43, 10, 9, 68, 16, 83, 98, 13, 61, 90, 44, 10, 45, 3]
